jungle/jungle/urls.py
from django.contrib import admin
from django.urls import path, include
from django_otp.admin import OTPAdminSite

admin.site.__class__ = OTPAdminSite

urlpatterns = [
    path('', include("frontend.urls")),
    path('cv/', include("yancv.urls")),
    path('ycrawl/', include("ycrawl.urls")),
    path('play/', include("play.urls")),
    path('vision/', include("vision.urls")),
    path('msg/', include("messenger.urls")),
    path('my/', include("webreader.urls")),
    path('admin/', admin.site.urls),
]

# Enforce 2FA only in production.
# if not settings.DEBUG:

jungle/play/urls.py
from django.urls import path

from . import views

app_name = "play"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # path('', views.index, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:question_id>/', views.detail, name='detail'),
    path('<int:pk>/results/', views.ResultView.as_view(), name='results'),
    # path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

jungle/ycrawl/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'actions', views.VmActionLogViewSet)
router.register(r'trails', views.VmTrailViewSet)
router.register(r'vms', views.VmViewSet)
router.register(r'configs', views.YCrawlConfigViewSet)
router.register(r'joblist', views.BatchJobListViewSet)

# api login page disabled, use admin page
app_name = "ycrawl"
urlpatterns = [
    path('', include(router.urls)),
#    path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

jungle/play/models.py
from django.contrib import admin
from django.db import models
from django.utils import timezone
from datetime import timedelta

# Create your models here.
class Question(models.Model):
    q_text = models.CharField("question text", max_length=999)
    pub_date = models.DateTimeField('date published')


    def __str__(self):
        return self.q_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Renctly published?'
    )
    def is_recent(self):
        return (timezone.now() - timedelta(days=3)) <= self.pub_date <= timezone.now()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField("choice text", max_length=999)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

jungle/play/views.py
from django.urls import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.views import generic
from django.shortcuts import get_object_or_404, render
from .models import *

# Create your views here.

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        sel_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'play/detail.html', {
            'question': question,
            'error_message': "Please select one choice."
        })
    else:
        sel_choice.votes += 1
        sel_choice.save()

    return HttpResponseRedirect(reverse('play:results', args=(question_id,)))

# using generic view to simply process, equivalent to commented area below
class IndexView(generic.ListView):
    template_name = "play/index.html"
    contenxt_object_name = 'question_list'

    def get_queryset(self):
        # very speical notation for LessThanEqual
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:3]


class DetailView(generic.DetailView):
    template_name = "play/detail.html"
    model = Question

    def get_queryset(self):
        """Excludes any questions that aren't published yet."""
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultView(generic.DetailView):
    template_name = "play/results.html"
    model = Question


# Below is equivalent to the short code above
# def index(request):
#     latest_qs = Question.objects.order_by('-pub_date')[:5]
#     return render(request, 'index.html', {"question_list": latest_qs})


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     # above shortcut is equivalent to below
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404(f"Question does not exist for id={question_id}")
#     return render(request, "detail.html", {'question': question})


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'results.html', {'question': question})

jungle/play/templates/play/detail.html
<form action="{% url 'play:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.q_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

jungle/play/templates/play/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'play/style.css' %}">

{% if question_list %}
    <p>Using percent-url viewname parm: Django will search for the url from correct urls.py</p>
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'play:detail' question.id %}">[{{question.id}}] {{ question.q_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No published question available.</p>
{% endif %}

jungle/play/templates/play/results.html
<h1>{{ question.q_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'play:detail' question.id %}">Vote again?</a>